const dummyData = [
  {
    name: "Non Veg Thali",
    price: "₹340",
    description:
      "Chicken + Dry fry + Jerre + Rice + Butter Roti (3psc) + Sweet + Salad/Pickle",
    category: "Hamburger",
  },
  {
    name: "Veg Pizza",
    price: "₹250",
    description: "Vegetable toppings + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Coca Cola",
    price: "₹50",
    description: "300ml can",
    category: "Drinks",
  },
  {
    name: "Chicken Burger",
    price: "₹150",
    description: "Grilled chicken patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Cold Coffee",
    price: "₹80",
    description: "Iced coffee with milk and sugar",
    category: "Drinks",
  },
  {
    name: "Veggie Delight Pizza",
    price: "₹280",
    description: "Mixed vegetables + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Spicy Chicken Wings",
    price: "₹200",
    description: "Crispy fried chicken wings with a spicy coating",
    category: "Hamburger",
  },
  {
    name: "Mojito",
    price: "₹60",
    description: "Refreshing lime and mint drink with soda water",
    category: "Drinks",
  },
  {
    name: "Margherita Pizza",
    price: "₹230",
    description: "Tomato sauce + Cheese + Basil leaves + Pizza base",
    category: "Pizza",
  },
  {
    name: "Veg Burger",
    price: "₹120",
    description: "Vegetable patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Orange Juice",
    price: "₹70",
    description: "Freshly squeezed orange juice",
    category: "Drinks",
  },
  {
    name: "Paneer Tikka Pizza",
    price: "₹270",
    description: "Paneer tikka pieces + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Chicken Wrap",
    price: "₹180",
    description: "Grilled chicken + lettuce + tomato + mayonnaise in a wrap",
    category: "Hamburger",
  },
  {
    name: "Iced Tea",
    price: "₹90",
    description: "Chilled tea with lemon and sugar",
    category: "Drinks",
  },
  {
    name: "Pepperoni Pizza",
    price: "₹250",
    description: "Pepperoni slices + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Veggie Sandwich",
    price: "₹100",
    description: "Mixed vegetables + cheese in sandwich bread",
    category: "Hamburger",
  },
  {
    name: "Mango Shake",
    price: "₹120",
    description: "Thick mango shake with milk and sugar",
    category: "Drinks",
  },
  {
    name: "Cheese Burst Pizza",
    price: "₹300",
    description: "Extra cheese + Cheese stuffed crust + Pizza base",
    category: "Pizza",
  },
  {
    name: "Paneer Burger",
    price: "₹140",
    description: "Paneer patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Lemonade",
    price: "₹80",
    description: "Refreshing lemon drink with sugar and water",
    category: "Drinks",
  },
  // Additional dummy data with more categories
  {
    name: "Cheeseburger",
    price: "₹170",
    description: "Beef patty + cheese + lettuce + tomato + onion + pickles",
    category: "Hamburger",
  },
  {
    name: "Green Tea",
    price: "₹60",
    description: "Green tea leaves + hot water",
    category: "Drinks",
  },
  {
    name: "BBQ Chicken Pizza",
    price: "₹300",
    description: "BBQ chicken + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Fries",
    price: "₹80",
    description: "Crispy potato fries",
    category: "Appetizer",
  },
  {
    name: "Milkshake",
    price: "₹120",
    description: "Thick milkshake with various flavors",
    category: "Drinks",
  },
  {
    name: "Onion Rings",
    price: "₹100",
    description: "Crispy battered onion rings",
    category: "Appetizer",
  },
  {
    name: "Bruschetta",
    price: "₹120",
    description:
      "Toasted bread topped with tomatoes, garlic, basil, and olive oil",
    category: "Appetizer",
  },
  {
    name: "Nachos",
    price: "₹150",
    description:
      "Tortilla chips topped with cheese, jalapeños, sour cream, and salsa",
    category: "Appetizer",
  },
  {
    name: "Mozzarella Sticks",
    price: "₹130",
    description: "Breaded and fried mozzarella cheese sticks",
    category: "Appetizer",
  },
  {
    name: "Garlic Bread",
    price: "₹90",
    description: "Toasted bread topped with garlic butter",
    category: "Appetizer",
  },
  {
    name: "Non Veg Thali",
    price: "₹340",
    description:
      "Chicken + Dry fry + Jerre + Rice + Butter Roti (3psc) + Sweet + Salad/Pickle",
    category: "Hamburger",
  },
  {
    name: "Veg Pizza",
    price: "₹250",
    description: "Vegetable toppings + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Coca Cola",
    price: "₹50",
    description: "300ml can",
    category: "Drinks",
  },
  {
    name: "Chicken Burger",
    price: "₹150",
    description: "Grilled chicken patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Cold Coffee",
    price: "₹80",
    description: "Iced coffee with milk and sugar",
    category: "Drinks",
  },
  {
    name: "Veggie Delight Pizza",
    price: "₹280",
    description: "Mixed vegetables + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Spicy Chicken Wings",
    price: "₹200",
    description: "Crispy fried chicken wings with a spicy coating",
    category: "Hamburger",
  },
  {
    name: "Mojito",
    price: "₹60",
    description: "Refreshing lime and mint drink with soda water",
    category: "Drinks",
  },
  {
    name: "Margherita Pizza",
    price: "₹230",
    description: "Tomato sauce + Cheese + Basil leaves + Pizza base",
    category: "Pizza",
  },
  {
    name: "Veg Burger",
    price: "₹120",
    description: "Vegetable patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Orange Juice",
    price: "₹70",
    description: "Freshly squeezed orange juice",
    category: "Drinks",
  },
  {
    name: "Paneer Tikka Pizza",
    price: "₹270",
    description: "Paneer tikka pieces + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Chicken Wrap",
    price: "₹180",
    description: "Grilled chicken + lettuce + tomato + mayonnaise in a wrap",
    category: "Hamburger",
  },
  {
    name: "Iced Tea",
    price: "₹90",
    description: "Chilled tea with lemon and sugar",
    category: "Drinks",
  },
  {
    name: "Pepperoni Pizza",
    price: "₹250",
    description: "Pepperoni slices + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Veggie Sandwich",
    price: "₹100",
    description: "Mixed vegetables + cheese in sandwich bread",
    category: "Hamburger",
  },
  {
    name: "Mango Shake",
    price: "₹120",
    description: "Thick mango shake with milk and sugar",
    category: "Drinks",
  },
  {
    name: "Cheese Burst Pizza",
    price: "₹300",
    description: "Extra cheese + Cheese stuffed crust + Pizza base",
    category: "Pizza",
  },
  {
    name: "Paneer Burger",
    price: "₹140",
    description: "Paneer patty + lettuce + tomato + mayonnaise",
    category: "Hamburger",
  },
  {
    name: "Lemonade",
    price: "₹80",
    description: "Refreshing lemon drink with sugar and water",
    category: "Drinks",
  },
  // Additional dummy data with more categories
  {
    name: "Cheeseburger",
    price: "₹170",
    description: "Beef patty + cheese + lettuce + tomato + onion + pickles",
    category: "Hamburger",
  },
  {
    name: "Green Tea",
    price: "₹60",
    description: "Green tea leaves + hot water",
    category: "Drinks",
  },
  {
    name: "BBQ Chicken Pizza",
    price: "₹300",
    description: "BBQ chicken + Cheese + Pizza base",
    category: "Pizza",
  },
  {
    name: "Fries",
    price: "₹80",
    description: "Crispy potato fries",
    category: "Appetizer",
  },
  {
    name: "Milkshake",
    price: "₹120",
    description: "Thick milkshake with various flavors",
    category: "Drinks",
  },
  {
    name: "Onion Rings",
    price: "₹100",
    description: "Crispy battered onion rings",
    category: "Appetizer",
  },
  {
    name: "Bruschetta",
    price: "₹120",
    description:
      "Toasted bread topped with tomatoes, garlic, basil, and olive oil",
    category: "Appetizer",
  },
  {
    name: "Nachos",
    price: "₹150",
    description:
      "Tortilla chips topped with cheese, jalapeños, sour cream, and salsa",
    category: "Appetizer",
  },
  {
    name: "Mozzarella Sticks",
    price: "₹130",
    description: "Breaded and fried mozzarella cheese sticks",
    category: "Appetizer",
  },
  {
    name: "Garlic Bread",
    price: "₹90",
    description: "Toasted bread topped with garlic butter",
    category: "Appetizer",
  },
];

export default dummyData;
